### ISSUE TITLE
tslib 版本太低

### ISSUE THREAD

**Issue by zfha** [antvis/algorithm#57]
[1] ../node_modules/@antv/algorithm/es/gaddi.js 498:59-72
[1] "export '__spreadArray' was not found in 'tslib'
[1]     at HarmonyImportSpecifierDependency._getErrors (/Users/fanzhou/Documents/code/tcv/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
[1]     at HarmonyImportSpecifierDependency.getWarnings (/Users/fanzhou/Documents/code/tcv/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:60:15)
[1]     at Compilation.reportDependencyErrorsAndWarnings (/Users/fanzhou/Documents/code/tcv/node_modules/webpack/lib/Compilation.js:1454:24)
[1]     at /Users/fanzhou/Documents/code/tcv/node_modules/webpack/lib/Compilation.js:1258:10
[1]     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/fanzhou/Documents/code/tcv/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
[1]     at AsyncSeriesHook.lazyCompileHook (/Users/fanzhou/Documents/code/tcv/node_modules/tapable/lib/Hook.js:154:20)
[1]     at Compilation.finish (/Users/fanzhou/Documents/code/tcv/node_modules/webpack/lib/Compilation.js:1253:28)
[1]     at /Users/fanzhou/Documents/code/tcv/node_modules/webpack/lib/Compiler.js:672:17
[1]     at _done (eval at create (/Users/fanzhou/Documents/code/tcv/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
[1]     at eval (eval at create (/Users/fanzhou/Documents/code/tcv/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:68:22)
[1]     at /Users/fanzhou/Documents/code/tcv/node_modules/webpack/lib/Compilation.js:1185:12
[1]     at /Users/fanzhou/Documents/code/tcv/node_modules/webpack/lib/Compilation.js:1097:9
[1]     at processTicksAndRejections (node:internal/process/task_queues:78:11)
[1]  @ ../node_modules/@antv/algorithm/es/index.js
[1]  @ ../node_modules/@antv/g6-pc/es/index.js
[1]  @ ../node_modules/@antv/g6/es/index.js
[1]  @ ../src/pages/tcbi/routes/cube/edit/panels/RightTopLink/VisualLink/utils/convert.ts
[1]  @ ../src/pages/tcbi/routes/cube/edit/panels/RightTopLink/VisualLink/VisualLink.tsx
[1]  @ ../src/pages/tcbi/routes/cube/edit/panels/RightTopLink/RightTopLink.tsx
[1]  @ ../src/pages/tcbi/routes/cube/edit/EditWorkbench.tsx
[1]  @ ../src/pages/tcbi/routes/cube/index.tsx
[1]  @ ../src/pages/tcbi/routes/index.tsx
[1]  @ ../src/pages/tcbi/app/Root.tsx
[1]  @ ../src/pages/tcbi/app/App.tsx
[1]  @ ../src/pages/tcbi-publish/init.tsx
[1]  @ ../src/pages/tcbi-publish/index.ts

**Comment by zfha** [comment]
<img width="1344" alt="企业微信截图_2c4727e0-5945-4b76-811d-89ff2c14c80d" src="https://user-images.githubusercontent.com/4082233/176629527-a5cd77f3-84df-4f3b-9ac2-fb5d820a47d3.png">
